SECRET_KEY = "your-super-secret-key"
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 3600
BASE_DATA_DIR = "/home/nurtilek/Desktop/yt_asr_data/"
GEMINI_API_KEY_OLD = "AIzaSyDo-TmbWT9_Qd3Hwo2DIf1bVCJae4FLcvg"
GEMINI_API_KEY = "AIzaSyDZyWrzECM4NIY6mTS_HE3K5xsTzHNIZBQ"